set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g prefix C-Space
unbind C-b
bind-key C-Space send-prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

# set windows and panes at 1 not 0
set -g base-index 1
set -g pane-base-index 1

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
# set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes
set -g @plugin 'catppuccin/tmux#v2.1.3'

# set catppuccin theme
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_current_number_color "#{@thm_lavender}"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"

# module customization
set -g @catppuccin_date_time_text " %m/%d %H:%M"

# status customization
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
# set -agF status-right "#{@catppuccin_status_directory}"
# set -agF status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_date_time}"


# set -g @resurrect-hook-post-restore-all 'tmux source-file ~/.config/tmux/tmux.conf'
# set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'
# set -g @resurrect-dir '~/.config/tmux/resurrect'
# set -g @continuum-save-interval '30'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run ~/.config/tmux/plugins/catppuccin/tmux/cattpuccin.tmux

run '~/.config/tmux/plugins/tpm/tpm'
